version: '3.8'
services:
  mqtt-broker:
    container_name: smartwave_mqtt_broker
    restart: always
    build: mqtt/.
    ports:
      - "9002:9001"
      - "1884:1883"
    networks:
      - db_network
      - web_network
  frontend:
    container_name: smartwave_frontend
    restart: always
    build: .
    ports:
      - "8080:5005"
    networks:
      - db_network
      - web_network
    volumes:
    - ./.env:/.env
    - ./ismartwave.sqlite3:/ismartwave.sqlite3
    depends_on:
      - mqtt-broker
  # nginx:
  #   container_name: nginx
  #   restart: always
  #   image: "nginx:latest"
  #   ports:
  #     - "8080:5085"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  #   networks:
  #     - web_network
  #   depends_on: 
  #     - ishield-aoa-frontend
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 